/**
 * Token logo lookup, layered across three sources:
 *
 *   0. Bundled seed list — `./seed-logos.json`
 *      ~120 entries (top tokens per supported chain by global market cap)
 *      shipped inside the JS bundle. Seeded into the map synchronously at
 *      module init so the most common rows (ETH, USDC, USDT, WBTC, WMON,
 *      …) render with the real logo on first paint, before either network
 *      list returns. Generated by
 *      `pnpm --filter @workspace/scripts run build-seed-logos`.
 *
 *   1. Uniswap default token list — https://tokens.uniswap.org/
 *      ~1,500 hand-curated tokens across 24 chains, each with a `logoURI`
 *      pulled from CoinGecko / TrustWallet / etc. Smaller, higher signal.
 *
 *   2. CoinGecko per-platform token lists —
 *      https://tokens.coingecko.com/{platform}/all.json
 *      ~10k+ tokens per major chain, vetted by the CoinGecko team. CORS-
 *      friendly and bulk-fetched, so no per-coin API rate limits apply.
 *
 * All three are merged into one in-memory map keyed by `chainId:address`.
 * The seed populates the map first, then CoinGecko, then Uniswap on top
 * (Uniswap is the most curated, so it wins on address collisions). The
 * seed is only ever a fallback for the long-tail network fetches — once
 * those land, their entries override the seed for the same address.
 * Both fetches run in parallel; either failing independently doesn't
 * block the other.
 *
 * Native gas tokens (MON, ETH) aren't in either list (token lists only
 * cover ERC-20s), so we override with hardcoded official URLs per chain
 * via `NATIVE_LOGO_BY_CHAIN`.
 *
 * Tokens with no match in either source resolve to `null` — the caller
 * is expected to render a neutral mark (see `TokenMark`) instead of any
 * generated / placeholder image. We don't return colorful synthetic
 * avatars from this module so an unknown scam token can never look like
 * it has an "official" identity.
 */

import seedLogos from "./seed-logos.json";

interface TokenListEntry {
  chainId: number;
  address: string;
  symbol?: string;
  name?: string;
  decimals?: number;
  logoURI?: string;
}

interface TokenList {
  tokens: TokenListEntry[];
}

interface SeedLogoEntry {
  chainId: number;
  address: string;
  logoURI: string;
  symbol: string;
}

const UNISWAP_LIST_URL = "https://tokens.uniswap.org/";

// CoinGecko's per-platform token list URL pattern. Slugs are CoinGecko's
// "asset_platform_id" values — these are stable and listed at
// https://api.coingecko.com/api/v3/asset_platforms.
//
// Map our supported `chainId`s to their CoinGecko platform slug. For chains
// CoinGecko doesn't index (Monad testnet today), set to `null` and the
// fetch is skipped — the resolver falls back to Uniswap's coverage if any,
// otherwise a neutral mark.
//
// Slugs verified against https://api.coingecko.com/api/v3/asset_platforms
// (look for `chain_identifier === <our chainId>`). Last verified 2026-05-01:
//   • chain 1   → "ethereum"
//   • chain 143 → "monad"   (https://tokens.coingecko.com/monad/all.json
//                            returns ~70 ERC-20s with logos: WMON, USDC,
//                            USDT, WBTC, WETH, aprMON, shMON, …)
//   • chain 10143 (Monad testnet) → not indexed by CoinGecko
const COINGECKO_PLATFORM_BY_CHAIN: Record<number, string | null> = {
  1: "ethereum",
  143: "monad",
  10143: null,
};

function coingeckoListUrl(platform: string): string {
  return `https://tokens.coingecko.com/${platform}/all.json`;
}

// Bumped to v3 (was v2) on 2026-05-01: prior cached entries on Monad
// mainnet (chainId 143) may have been written before the CoinGecko
// "monad" platform list was confirmed available, so any client with a
// stale v2 cache could be missing real logos for WMON/USDC/USDT/etc.
// Bumping the key forces a one-time refetch instead of waiting on the
// 24h TTL.
const STORAGE_KEY = "nb_token_logo_map_v3";
const TTL_MS = 24 * 60 * 60 * 1000; // 24h

// Native (gas) token logos by chain ID. Sourced from CoinGecko's official
// per-coin image CDN so the native row uses the same canonical brand as
// every ERC-20 we render. URLs verified live on 2026-05-01:
// • Ethereum mainnet (1) → CoinGecko coin id `ethereum` (image #279)
// • Monad mainnet (143)  → CoinGecko coin id `monad`    (image #38927)
const NATIVE_LOGO_BY_CHAIN: Record<number, string> = {
  1: "https://coin-images.coingecko.com/coins/images/279/small/ethereum.png?1696501628",
  143: "https://coin-images.coingecko.com/coins/images/38927/small/mon.png?1766029057",
};

// Map "chainId:lowercaseAddress" → logoURI.
//
// Initialized synchronously from the bundled seed list (see `seedLogos`
// import above) so the most common rows render with real logos on first
// paint, before any network fetch completes. `ensureLoaded()` later
// layers Uniswap + CoinGecko on top of the seed.
let logoMap: Map<string, string> = seedLogosToMap();
// Tracks whether we've finished the cache-or-network hydration step.
// Distinct from `logoMap` being non-null because the seed populates the
// map synchronously at module init — without this flag, `ensureLoaded()`
// would short-circuit on the seed and never fetch the long tail.
let hydrated = false;
let inFlight: Promise<Map<string, string>> | null = null;

function seedLogosToMap(): Map<string, string> {
  const m = new Map<string, string>();
  for (const e of seedLogos as SeedLogoEntry[]) {
    if (typeof e.address !== "string" || typeof e.chainId !== "number") continue;
    if (typeof e.logoURI !== "string" || !e.logoURI) continue;
    m.set(`${e.chainId}:${e.address.toLowerCase()}`, e.logoURI);
  }
  return m;
}

// Bumped every time `logoMap` is replaced (cache hit, network completion).
// Components subscribe via `useTokenLogosVersion()` so that rows render with
// the neutral fallback first, then deterministically re-render with real
// logos as soon as the lists hydrate — no waiting for an unrelated re-render
// to happen to pick up the new map.
let version = 0;
const listeners = new Set<() => void>();

function bumpVersion(): void {
  version++;
  for (const l of listeners) l();
}

export function subscribeTokenLogos(listener: () => void): () => void {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

export function getTokenLogosVersion(): number {
  return version;
}

function key(chainId: number, address: string): string {
  return `${chainId}:${address.toLowerCase()}`;
}

// Merge a token list into an existing map. Always overwrites on
// collision — caller controls precedence by ordering the merge calls
// (the last list merged wins).
function mergeList(m: Map<string, string>, list: TokenList): void {
  for (const t of list.tokens) {
    if (typeof t.address !== "string" || typeof t.chainId !== "number") continue;
    if (typeof t.logoURI !== "string" || !t.logoURI) continue;
    m.set(key(t.chainId, t.address), t.logoURI);
  }
}

interface CachedShape {
  at: number;
  entries: [string, string][];
}

function readCache(): Map<string, string> | null {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as CachedShape;
    if (typeof parsed?.at !== "number") return null;
    if (!Array.isArray(parsed.entries)) return null;
    if (Date.now() - parsed.at > TTL_MS) return null;
    return new Map(parsed.entries);
  } catch {
    return null;
  }
}

function writeCache(m: Map<string, string>): void {
  try {
    const payload: CachedShape = { at: Date.now(), entries: Array.from(m) };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(payload));
  } catch {
    // localStorage full / blocked — silently skip
  }
}

async function fetchList(url: string): Promise<TokenList | null> {
  try {
    const r = await fetch(url, { mode: "cors" });
    if (!r.ok) return null;
    const data = (await r.json()) as TokenList;
    if (!data || !Array.isArray(data.tokens)) return null;
    return data;
  } catch {
    return null;
  }
}

async function ensureLoaded(): Promise<Map<string, string>> {
  if (hydrated) return logoMap;
  const cached = readCache();
  if (cached) {
    // Cache is a snapshot of the previous full hydration (seed + Uniswap +
    // CoinGecko). Layer it over the seed so any newer seed entries shipped
    // in this build still take effect even when an older cache is present.
    for (const [k, v] of cached) logoMap.set(k, v);
    hydrated = true;
    bumpVersion();
    return logoMap;
  }
  if (inFlight) return inFlight;
  inFlight = (async () => {
    try {
      // Run Uniswap + every CoinGecko platform list in parallel. A null
      // result from any single source just means "no coverage from that
      // source" — never throws, never blocks the others.
      const platformSlugs = Array.from(
        new Set(
          Object.values(COINGECKO_PLATFORM_BY_CHAIN).filter(
            (p): p is string => typeof p === "string" && p.length > 0,
          ),
        ),
      );
      const [uniswap, ...coingeckoLists] = await Promise.all([
        fetchList(UNISWAP_LIST_URL),
        ...platformSlugs.map((p) => fetchList(coingeckoListUrl(p))),
      ]);
      // Start from the seed so we keep coverage for the common rows even
      // if both network fetches fail. CoinGecko then layers on top, then
      // Uniswap last so its more curated entries win on collision.
      const m = new Map(logoMap);
      for (const list of coingeckoLists) {
        if (list) mergeList(m, list);
      }
      if (uniswap) mergeList(m, uniswap);
      writeCache(m);
      logoMap = m;
      hydrated = true;
      bumpVersion();
      return m;
    } finally {
      // Always clear so a transient failure doesn't pin a stuck rejected
      // promise and block every later caller from retrying.
      inFlight = null;
    }
  })();
  return inFlight;
}

if (typeof window !== "undefined") {
  void ensureLoaded();
}

/**
 * Resolves the native gas-token logo for a chain (MON, ETH, etc.). Returns
 * null when we don't have one configured.
 */
export function getNativeLogo(chainId: number): string | null {
  return NATIVE_LOGO_BY_CHAIN[chainId] ?? null;
}

/**
 * Synchronous lookup for an ERC-20 logo. Returns the URL if we have one
 * for that `(chainId, address)` — either from the bundled seed list (which
 * is populated at module init), the localStorage cache, or a completed
 * network fetch — otherwise null. Does not handle the "native" sentinel;
 * see `resolveTokenLogo` for the unified resolver.
 */
export function getTokenLogo(chainId: number, address: string): string | null {
  return logoMap.get(key(chainId, address)) ?? null;
}

/**
 * Unified resolver used by every render site. Returns:
 *  - the canonical native-gas logo when `address === "native"`
 *  - the Uniswap- or CoinGecko-hosted logoURI for a known ERC-20
 *  - `null` for everything else (caller renders a neutral `TokenMark`)
 *
 * Never returns a generated / placeholder image. For the long-tail of
 * tokens not in the bundled seed list, this returns null until the
 * Uniswap + CoinGecko fetches hydrate — the caller falls back to the
 * neutral mark and re-renders once the lists land.
 */
export function resolveTokenLogo(
  chainId: number,
  address: string,
): string | null {
  if (address === "native") return getNativeLogo(chainId);
  return getTokenLogo(chainId, address);
}

export function primeTokenLogos(): Promise<Map<string, string>> {
  return ensureLoaded();
}
